apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: team-permissions
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
{{- range .Values.team.members }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
{{- end }}